name: Test First Python Project

on:
  push:
    paths:
      - 'first-exercise/**'
  pull_request:
    paths:
      - 'first-exercise/**'

jobs:
  test-project-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('first-exercise/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd first-exercise
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          cd first-exercise
          flake8 . --exclude=venv --max-line-length=105

      - name: Run tests
        run: |
          cd first-exercise
          pytest tests/test_main.py
